name: Run KJnews

on:
  schedule:
    - cron: '7 * * * *'
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install --upgrade pip
             pip install -r requirements.txt
             pip install webdriver-manager selenium
             pip install undetected-chromedriver
             pip install chromedriver-py
      - name: Download and Install Poppler
        run: |
          wget https://poppler.freedesktop.org/poppler-24.07.0.tar.xz
          tar -xf poppler-24.07.0.tar.xz
          cd poppler-24.07.0
          mkdir build
          cd build
          cmake -DENABLE_NSS3=OFF -DENABLE_GPGME=OFF -DENABLE_QT6=OFF ..
          make
          sudo make install

      - name: Run KJnews
        run: python main.py
        env: 
          LINE_NOTIFY_ID: ${{ secrets.LINE_NOTIFY_ID }}
          GOOGLE_SHEETS_KEY: ${{ secrets.GOOGLE_SHEETS_KEY }}
          GS_CREDENTIALS: ${{ secrets.GS_CREDENTIALS }}
